./run.sh org.roaringbitmap.runcontainer.MappedRunContainerRealDataBenchmarkWideAnd > mwideandlog.txt
./run.sh org.roaringbitmap.runcontainer.MappedRunContainerRealDataBenchmarkWideOrPQ > mwideorpqlog.txt
./run.sh org.roaringbitmap.runcontainer.MappedRunContainerRealDataBenchmarkRunOptimize > mserializelog.txt
./run.sh org.roaringbitmap.runcontainer.RunContainerRealDataBenchmarkWideAnd > wideandlog.txt
./run.sh org.roaringbitmap.runcontainer.RunContainerRealDataBenchmarkWideOrPQ > wideorpqlog.txt
./run.sh org.roaringbitmap.runcontainer.RunContainerRealDataBenchmarkRunOptimize > serializelog.txt
./run.sh org.roaringbitmap.realdata.RealDataBenchmarkAnd > andlog.txt
./run.sh org.roaringbitmap.realdata.RealDataBenchmarkAndNot > andnotlog.txt
./run.sh org.roaringbitmap.realdata.RealDataBenchmarkContains > containslog.txt
./run.sh org.roaringbitmap.realdata.RealDataBenchmarkIterate > iteratelog.txt
./run.sh org.roaringbitmap.realdata.RealDataBenchmarkOr > orlog.txt
./run.sh org.roaringbitmap.realdata.RealDataBenchmarkWideOrNaive > wideornaivelog.txt
./run.sh org.roaringbitmap.realdata.RealDataBenchmarkXor > xorlog.txt