./run.sh org.roaringbitmap.runcontainer.MappedRunContainerRealDataBenchmarkWideAnd > mwideandlog.txt
./run.sh org.roaringbitmap.runcontainer.MappedRunContainerRealDataBenchmarkWideOrNaive > mwideornaivelog.txt
./run.sh org.roaringbitmap.runcontainer.MappedRunContainerRealDataBenchmarkWideOrPQ > mwideorpqlog.txt
./run.sh org.roaringbitmap.runcontainer.MappedRunContainerRealDataBenchmarkIterate > miteratelog.txt
./run.sh org.roaringbitmap.runcontainer.MappedRunContainerRealDataBenchmarkAnd.pairwise > mandlog.txt
./run.sh org.roaringbitmap.runcontainer.MappedRunContainerRealDataBenchmarkOr > morlog.txt
./run.sh org.roaringbitmap.runcontainer.MappedRunContainerRealDataBenchmarkRunOptimize > mserializelog.txt
./run.sh org.roaringbitmap.runcontainer.RunContainerRealDataBenchmarkWideAnd > wideandlog.txt
./run.sh org.roaringbitmap.runcontainer.RunContainerRealDataBenchmarkWideOrNaive > wideornaivelog.txt
./run.sh org.roaringbitmap.runcontainer.RunContainerRealDataBenchmarkWideOrPQ > wideorpqlog.txt
./run.sh org.roaringbitmap.runcontainer.RunContainerRealDataBenchmarkIterate > iteratelog.txt
./run.sh org.roaringbitmap.runcontainer.RunContainerRealDataBenchmarkAndNot > andnotlog.txt
./run.sh org.roaringbitmap.runcontainer.RunContainerRealDataBenchmarkAnd.pairwise > andlog.txt
./run.sh org.roaringbitmap.runcontainer.RunContainerRealDataBenchmarkOr > orlog.txt
./run.sh org.roaringbitmap.runcontainer.RunContainerRealDataBenchmarkXor > xorlog.txt
./run.sh org.roaringbitmap.runcontainer.RunContainerRealDataBenchmarkRunOptimize > serializelog.txt
./run.sh org.roaringbitmap.realdata.RealDataBenchmarkContains > containslog.txt
